// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	session "github.com/vdrpkv/goexamples/internal/chat/domain/session"

	user "github.com/vdrpkv/goexamples/internal/chat/domain/user"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateActiveSession provides a mock function with given fields: ctx, userID
func (_m *Repository) CreateActiveSession(ctx context.Context, userID user.ID) (*session.Entity, error) {
	ret := _m.Called(ctx, userID)

	var r0 *session.Entity
	if rf, ok := ret.Get(0).(func(context.Context, user.ID) *session.Entity); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.Entity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, user.ID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateOrFindUser provides a mock function with given fields: ctx, userName
func (_m *Repository) CreateOrFindUser(ctx context.Context, userName user.Name) (*user.Entity, error) {
	ret := _m.Called(ctx, userName)

	var r0 *user.Entity
	if rf, ok := ret.Get(0).(func(context.Context, user.Name) *user.Entity); ok {
		r0 = rf(ctx, userName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.Entity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, user.Name) error); ok {
		r1 = rf(ctx, userName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
