// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	enter "github.com/vdrpkv/goexamples/internal/chat/domain/session/usecase/enter"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// Do provides a mock function with given fields: ctx, args
func (_m *UseCase) Do(ctx context.Context, args *enter.Args) (*enter.Result, error) {
	ret := _m.Called(ctx, args)

	var r0 *enter.Result
	if rf, ok := ret.Get(0).(func(context.Context, *enter.Args) *enter.Result); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*enter.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *enter.Args) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUseCase(t mockConstructorTestingTNewUseCase) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
